### ISSUE TITLE
package names should be all lowercase

### ISSUE THREAD

**Issue by dcsan** [gadicc/meteor-SyntaxHighlighter#3]
I'm getting the error below. 

since this refers to how you have the package registered in atmosphere, and with the whole new packaging /namspacing system I think it would be best fixed by the author as they register the package?

```
=> Errors while scanning packages:

While reading package from `/Users/dc/dev/shumi/mewiki/app/packages/SyntaxHighlighter`:
error: Package names can only contain lowercase ASCII alphanumerics, dash, dot, or colon, not "S".

While reading package from `/Users/dc/dev/shumi/mewiki/app/packages/SyntaxHighlighter`:
error: Package names can only contain lowercase ASCII alphanumerics, dash, dot, or colon, not "S".

/usr/local/lib/node_modules/meteorite/lib/command.js:41
            throw "Command exited with " + code + "/" + signal;
                                                      ^
Command exited with 1/null
```

**Comment by gadicc** [comment]
hey, yeah, i "renamed" the package to "syntaxhighlighter" for 0.9.0.
unfortunately there's no official renaming capability yet, so essentially i just created a new package with that name.  on atmosphere too, to allow for easier upgrades.

so yeah just "meteor add gadicohen:syntaxhighlighter"

(the minute i can rename my namespace, it will become gadicc too... a bit shorter).

**Comment by npvn** [comment]
Hi @gadicc,

I tried to install the package with `meteor add gadicohen:syntaxhighlighter` but got this error:
`INCOMPATIBLE WITH METEOR 0.9.0 OR LATER`

Tried it on meteor 0.9.2.2 and 0.9.0. The result was the same.

P.S. Thanks for another useful package!

**Comment by gadicc** [comment]
hey, on meteor < 0.9.3-rc you need to "meteor show gadicohen:syntaxhighlighter"  and then "add"  the latest version explicitly with @version.  same with any other package which uses a dash ("-") in the version.  in latest meteor we can use ~ for wrapped packages and it understands it. 

p. s.  I'll be doing a wrapper for prism soon too when i have a chance, has support for handlebars syntax.

**Comment by npvn** [comment]
That method works well. Thank you.

I would love to help on the prism wrapper since I need to display some template code containing handlebars syntax. Not sure where to start though. Could you suggest an idea?

**Comment by gadicc** [comment]
Since 0.9.3 it will pickup the latest release without specifying explicitly.  `3.0.83_19` is the most current.

@npvn, very early days (it's not so configurable yet), but you can `meteor add gadicohen:prism`.  See the  README at https://atmospherejs.com/gadicohen/prism or https://github.com/gadicc/meteor-prism/

Note, there's no `handlebars` language in Prism (I didn't actually realize this when I started making the package, I got confused with highlight.js hehe), but within the smart package, you get access to a language called `blaze` which covers the handlebars syntax and also the `<template>` tags and HTML.  Any further discussion should be on that project page.
